namespace HL7Parser.Core;

/// <summary>
/// Maps HL7 segment IDs to ordered field-name arrays (index 0 = segment_id).
/// </summary>
public static class SegmentFields
{
    public static readonly Dictionary<string, string[]> Fields = new()
    {
        ["MSH"] = new[]
        {
            "segment_id", "field_separator", "encoding_chars",
            "sending_application", "sending_facility",
            "receiving_application", "receiving_facility",
            "datetime", "security", "message_type",
            "message_control_id", "processing_id", "version_id",
            "sequence_number", "continuation_pointer",
            "accept_ack_type", "application_ack_type",
            "country_code", "character_set", "principal_language",
        },
        ["EVN"] = new[]
        {
            "segment_id", "event_type_code", "recorded_datetime",
            "datetime_planned", "event_reason_code", "operator_id", "event_occurred",
        },
        ["PID"] = new[]
        {
            "segment_id", "set_id", "patient_id",
            "patient_identifier_list", "alt_patient_id",
            "patient_name", "mothers_maiden_name", "datetime_of_birth",
            "administrative_sex", "patient_alias", "race",
            "patient_address", "county_code", "phone_number_home",
            "phone_number_business", "primary_language", "marital_status",
            "religion", "patient_account_number", "ssn",
            "drivers_license", "mothers_identifier", "ethnic_group",
            "birth_place", "multiple_birth_indicator", "birth_order",
            "citizenship", "veterans_military_status", "nationality",
            "patient_death_datetime", "patient_death_indicator",
            "identity_unknown_indicator", "identity_reliability_code",
            "last_update_datetime", "last_update_facility",
            "species_code", "breed_code", "strain",
            "production_class_code", "tribal_citizenship",
        },
        ["PD1"] = new[]
        {
            "segment_id", "living_dependency", "living_arrangement",
            "patient_primary_facility", "patient_primary_care_provider",
            "student_indicator", "handicap", "living_will_code",
            "organ_donor_code", "separate_bill", "duplicate_patient",
            "publicity_code", "protection_indicator",
            "protection_indicator_effective_date", "place_of_worship",
            "advance_directive_code", "immunization_registry_status",
            "immunization_registry_effective_date",
            "publicity_code_effective_date", "military_branch",
            "military_rank_grade", "military_status",
            "advance_directive_last_verified_date",
        },
        ["MRG"] = new[]
        {
            "segment_id", "prior_patient_identifier_list",
            "prior_alternate_patient_id", "prior_patient_account_number",
            "prior_patient_id", "prior_visit_number",
            "prior_alternate_visit_id", "prior_patient_name",
        },
        ["DB1"] = new[]
        {
            "segment_id", "set_id", "disabled_person_code",
            "disabled_person_identifier", "disability_indicator",
            "disability_start_date", "disability_end_date",
            "disability_return_to_work_date",
        },
        ["PDA"] = new[]
        {
            "segment_id", "death_cause_code", "death_location",
            "death_certified_indicator", "death_certificate_signed_date_time",
            "death_certified_by", "autopsy_indicator",
            "autopsy_start_and_end_date_time", "autopsy_performed_by",
            "coroner_indicator",
        },
        ["ROL"] = new[]
        {
            "segment_id", "role_instance_id", "action_code", "role",
            "role_person", "role_begin_date_time", "role_end_date_time",
            "role_duration", "role_action_reason", "provider_type",
            "organization_unit_type", "office_home_address", "phone",
            "persons_location", "organization",
        },
        ["PV1"] = new[]
        {
            "segment_id", "set_id", "patient_class",
            "assigned_patient_location", "admission_type",
            "preadmit_number", "prior_patient_location",
            "attending_doctor", "referring_doctor", "consulting_doctor",
            "hospital_service", "temporary_location",
            "preadmit_test_indicator", "readmission_indicator",
            "admit_source", "ambulatory_status", "vip_indicator",
            "admitting_doctor", "patient_type", "visit_number",
            "financial_class", "charge_price_indicator", "courtesy_code",
            "credit_rating", "contract_code", "contract_effective_date",
            "contract_amount", "contract_period", "interest_code",
            "transfer_to_bad_debt", "transfer_to_bad_debt_date",
            "bad_debt_agency_code", "bad_debt_transfer_amount",
            "bad_debt_recovery_amount", "delete_account_indicator",
            "delete_account_date", "discharge_disposition",
            "discharged_to_location", "diet_type", "servicing_facility",
            "bed_status", "account_status", "pending_location",
            "prior_temporary_location", "admit_datetime",
            "discharge_datetime", "current_patient_balance",
            "total_charges", "total_adjustments", "total_payments",
            "alt_visit_id", "visit_indicator", "other_healthcare_provider",
        },
        ["PV2"] = new[]
        {
            "segment_id", "prior_pending_location", "accommodation_code",
            "admit_reason", "transfer_reason", "patient_valuables",
            "patient_valuables_location", "visit_user_code",
            "expected_admit_datetime", "expected_discharge_datetime",
            "estimated_length_of_stay", "actual_length_of_stay",
            "visit_description", "referral_source_code",
            "previous_service_date", "employment_illness_related",
            "purge_status_code", "purge_status_date",
            "special_program_code", "retention_indicator",
            "expected_number_of_insurance_plans", "visit_publicity_code",
            "visit_protection_indicator", "clinic_organization_name",
            "patient_status_code", "visit_priority_code",
            "previous_treatment_date", "expected_discharge_disposition",
            "signature_on_file_date", "first_similar_illness_date",
            "patient_charge_adjustment_code", "recurring_service_code",
            "billing_media_code", "expected_surgery_datetime",
            "military_partnership_code", "military_non_availability_code",
            "newborn_baby_indicator", "baby_detained_indicator",
            "mode_of_arrival_code", "recreational_drug_use_code",
            "admission_level_of_care_code", "precaution_code",
            "patient_condition_code", "living_will_code",
            "organ_donor_code", "advance_directive_code",
            "patient_status_effective_date", "expected_loa_return_datetime",
            "expected_pre_admission_testing_datetime", "notify_clergy_code",
        },
        ["NK1"] = new[]
        {
            "segment_id", "set_id", "name", "relationship", "address",
            "phone_number", "business_phone_number", "contact_role",
            "start_date", "end_date", "next_of_kin_job_title",
            "next_of_kin_job_code", "employee_number", "organization_name",
            "marital_status", "administrative_sex", "date_of_birth",
            "living_dependency", "ambulatory_status", "citizenship",
            "primary_language", "living_arrangement", "publicity_code",
            "protection_indicator", "student_indicator", "religion",
            "mothers_maiden_name", "nationality", "ethnic_group",
            "contact_reason", "contact_person_name", "contact_person_phone",
            "contact_person_address", "next_of_kin_identifier",
            "job_status", "race", "handicap", "contact_person_ssn",
            "born_in_country", "nationality_at_birth",
        },
        ["AL1"] = new[]
        {
            "segment_id", "set_id", "allergen_type_code", "allergen_code",
            "allergy_severity_code", "allergy_reaction_code", "identification_date",
        },
        ["IAM"] = new[]
        {
            "segment_id", "set_id", "allergen_type_code", "allergen_code",
            "allergy_severity_code", "allergy_reaction_code",
            "allergy_action_code", "allergy_unique_identifier",
            "action_reason", "sensitivity_to_causative_agent_code",
            "allergen_group_code", "onset_date", "onset_date_text",
            "reported_date_time", "reported_by",
            "relationship_to_patient_code", "alert_device_code",
            "allergy_clinical_status_code", "statused_by_person",
            "statused_by_organization", "statused_at_date_time",
            "inactivated_by_person", "inactivated_date_time",
            "initially_recorded_by_person", "initially_recorded_date_time",
            "modified_by_person", "modified_date_time", "clinic_id",
            "initial_adverse_reaction_report_unique_id",
            "adverse_reaction_report_unique_id",
        },
        ["DG1"] = new[]
        {
            "segment_id", "set_id", "diagnosis_coding_method",
            "diagnosis_code", "diagnosis_description", "diagnosis_datetime",
            "diagnosis_type", "major_diagnostic_category",
            "diagnostic_related_group", "drg_approval_indicator",
            "drg_grouper_review_code", "outlier_type", "outlier_days",
            "outlier_cost", "grouper_version", "diagnosis_priority",
            "diagnosing_clinician", "diagnosis_classification",
            "confidential_indicator", "attestation_datetime",
            "diagnosis_identifier", "diagnosis_action_code",
        },
        ["DRG"] = new[]
        {
            "segment_id", "diagnostic_related_group",
            "drg_assigned_date_time", "drg_approval_indicator",
            "drg_grouper_review_code", "outlier_type", "outlier_days",
            "outlier_cost", "drg_payor", "outlier_reimbursement",
            "confidential_indicator", "drg_transfer_type", "name_of_coder",
            "grouper_status", "pccl_value_code", "effective_weight",
            "monetary_amount", "status_patient", "grouper_software_name",
            "grouper_software_version", "status_financial_calculation",
            "relative_discount_surcharge", "basic_charge", "total_charge",
            "discount_surcharge", "calculated_days", "status_gender",
            "status_age", "status_length_of_stay", "status_same_day_flag",
            "status_separation_mode", "status_weight_at_birth",
            "status_respiration_minutes", "status_admission",
        },
        ["OBX"] = new[]
        {
            "segment_id", "set_id", "value_type", "observation_identifier",
            "observation_sub_id", "observation_value", "units",
            "references_range", "abnormal_flags", "probability",
            "nature_of_abnormal", "observation_result_status",
            "effective_date", "user_defined_access_checks",
            "datetime_of_observation", "producers_id",
            "responsible_observer", "observation_method",
            "equipment_instance_identifier", "datetime_of_analysis",
        },
        ["IN1"] = new[]
        {
            "segment_id", "set_id", "insurance_plan_id",
            "insurance_company_id", "insurance_company_name",
            "insurance_company_address", "insurance_co_contact_person",
            "insurance_co_phone_number", "group_number", "group_name",
            "insured_group_employer_id", "insured_group_employer_name",
            "plan_effective_date", "plan_expiration_date",
            "authorization_information", "plan_type", "name_of_insured",
            "insured_relationship_to_patient", "insured_date_of_birth",
            "insured_address", "assignment_of_benefits",
            "coordination_of_benefits", "coord_of_ben_priority",
            "notice_of_admission_flag", "notice_of_admission_date",
            "report_of_eligibility_flag", "report_of_eligibility_date",
            "release_information_code", "pre_admit_certification",
            "verification_datetime", "verification_by",
            "type_of_agreement_code", "billing_status",
            "lifetime_reserve_days", "delay_before_lr_day",
            "company_plan_code", "policy_number", "policy_deductible",
            "policy_limit_amount", "policy_limit_days",
            "room_rate_semi_private", "room_rate_private",
            "insured_employment_status", "insured_administrative_sex",
            "insured_employer_address", "verification_status",
            "prior_insurance_plan_id", "coverage_type", "handicap",
            "insured_id_number", "signature_code", "signature_code_date",
            "insured_birth_place", "vip_indicator",
        },
        ["IN2"] = new[]
        {
            "segment_id", "insured_employee_id",
            "insured_social_security_number", "insured_employer_name_and_id",
            "employer_information_data", "mail_claim_party",
            "medicare_health_ins_card_number", "medicaid_case_name",
            "medicaid_case_number", "champus_sponsor_name",
            "champus_id_number", "dependent_of_champus_recipient",
            "champus_organization", "champus_station", "champus_service",
            "champus_rank_grade", "champus_status", "champus_retire_date",
            "champus_non_avail_cert_on_file", "baby_coverage",
            "combine_baby_bill", "blood_deductible",
            "special_coverage_approval_name",
            "special_coverage_approval_title",
            "non_covered_insurance_code", "payor_id",
            "payor_subscriber_id", "eligibility_source",
            "room_coverage_type_amount", "policy_type_amount",
            "daily_deductible", "living_dependency", "ambulatory_status",
            "citizenship", "primary_language", "living_arrangement",
            "publicity_code", "protection_indicator", "student_indicator",
            "religion", "mothers_maiden_name", "nationality",
            "ethnic_group", "marital_status",
            "insured_employment_start_date", "employment_stop_date",
            "job_title", "job_code_class", "job_status",
            "employer_contact_person_name", "employer_contact_person_phone",
            "employer_contact_reason", "insured_contact_persons_name",
            "insured_contact_person_phone", "insured_contact_person_reason",
            "relationship_to_patient_start_date",
            "relationship_to_patient_stop_date",
            "insurance_co_contact_reason", "insurance_co_contact_phone",
            "policy_scope", "policy_source", "patient_member_number",
            "guarantor_relationship", "insured_phone_number_home",
            "insured_employer_phone_number",
            "military_handicapped_program", "suspend_flag",
            "copay_limit_flag", "stoploss_limit_flag",
            "insured_organization_name",
            "insured_employer_organization_name", "race",
            "patient_relationship_to_insured",
        },
        ["IN3"] = new[]
        {
            "segment_id", "set_id", "certification_number", "certified_by",
            "certification_required", "permit_auto_entry",
            "certification_status_code", "pre_certification_window",
            "pre_certification_identifier", "effective_date",
            "certification_expiration_date", "certification_agent",
            "certification_agency_phone", "pre_certification_req",
            "case_manager", "second_opinion_date", "second_opinion_status",
            "second_opinion_documentation_received",
            "second_opinion_practitioner", "certification_type",
            "certification_category",
        },
        ["GT1"] = new[]
        {
            "segment_id", "set_id", "guarantor_number", "guarantor_name",
            "guarantor_spouse_name", "guarantor_address",
            "guarantor_ph_num_home", "guarantor_ph_num_business",
            "guarantor_date_of_birth", "guarantor_administrative_sex",
            "guarantor_type", "guarantor_relationship", "guarantor_ssn",
            "guarantor_date_begin", "guarantor_date_end",
            "guarantor_priority", "guarantor_employer_name",
            "guarantor_employer_address", "guarantor_employer_phone",
            "guarantor_employee_id", "guarantor_employment_status",
            "guarantor_organization_name", "guarantor_billing_hold_flag",
            "guarantor_credit_rating_code", "guarantor_death_date_time",
            "guarantor_death_flag", "guarantor_charge_adjustment_code",
            "guarantor_household_annual_income", "guarantor_household_size",
            "guarantor_employer_id", "guarantor_marital_status_code",
            "guarantor_hire_effective_date", "employment_stop_date",
            "living_dependency", "ambulatory_status", "citizenship",
            "primary_language", "living_arrangement", "publicity_code",
            "protection_indicator", "student_indicator", "religion",
            "mothers_maiden_name", "nationality", "ethnic_group",
            "contact_persons_name", "contact_persons_phone",
            "contact_reason", "contact_relationship", "job_title",
            "job_code_class", "guarantor_employer_org_name", "handicap",
            "job_status", "guarantor_financial_class", "guarantor_race",
            "guarantor_birth_place", "vip_indicator",
        },
        ["RF1"] = new[]
        {
            "segment_id", "referral_status", "referral_priority",
            "referral_type", "referral_disposition", "referral_category",
            "originating_referral_identifier", "effective_date",
            "expiration_date", "process_date", "referral_reason",
            "external_referral_identifier",
            "referral_documentation_completion_status",
        },
        ["AUT"] = new[]
        {
            "segment_id", "authorizing_payer_plan_id",
            "authorizing_payer_company_id", "authorizing_payer_company_name",
            "authorization_effective_date", "authorization_expiration_date",
            "authorization_identifier", "reimbursement_limit",
            "requested_number_of_treatments", "authorized_number_of_treatments",
            "process_date", "requested_discipline", "authorized_discipline",
        },
        ["PRD"] = new[]
        {
            "segment_id", "provider_role", "provider_name",
            "provider_address", "provider_location",
            "provider_communication_info", "preferred_method_of_contact",
            "provider_identifiers", "effective_start_date",
            "effective_end_date", "provider_organization_name",
            "provider_organization_address", "provider_organization_location",
            "provider_org_communication_info",
            "provider_org_method_of_contact",
        },
        ["CTD"] = new[]
        {
            "segment_id", "contact_role", "contact_name", "contact_address",
            "contact_location", "contact_communication_info",
            "preferred_method_of_contact", "contact_identifiers",
        },
        ["CON"] = new[]
        {
            "segment_id", "set_id", "consent_type",
            "consent_form_id_and_version", "consent_form_number",
            "consent_text", "subject_specific_consent_text",
            "consent_background_info", "subject_specific_consent_background",
            "consenter_imposed_limitations", "consent_mode",
            "consent_status", "consent_discussion_date_time",
            "consent_decision_date_time", "consent_effective_date_time",
            "consent_end_date_time", "subject_competency_indicator",
            "translator_assistance_indicator", "language_translated_to",
            "informational_material_supplied", "consent_bypass_reason",
            "consent_disclosure_level", "consent_non_disclosure_reason",
            "non_subject_consenter_reason", "consenter_id",
            "relationship_to_subject",
        },
        ["VAR"] = new[]
        {
            "segment_id", "variance_instance_id", "documented_date_time",
            "stated_variance_date_time", "variance_originator",
            "variance_classification", "variance_description",
            "variance_originating_provider",
        },
        ["SCH"] = new[]
        {
            "segment_id", "placer_appointment_id", "filler_appointment_id",
            "occurrence_number", "placer_group_number", "schedule_id",
            "event_reason", "appointment_reason", "appointment_type",
            "appointment_duration", "appointment_duration_units",
            "appointment_timing_quantity", "placer_contact_person",
            "placer_contact_phone", "placer_contact_address",
            "placer_contact_location", "filler_contact_person",
            "filler_contact_phone", "filler_contact_address",
            "filler_contact_location", "entered_by_person",
            "entered_by_phone", "entered_by_location",
            "parent_placer_appointment_id", "parent_filler_appointment_id",
            "filler_status_code", "placer_order_number", "filler_order_number",
        },
        ["ARQ"] = new[]
        {
            "segment_id", "placer_appointment_id", "filler_appointment_id",
            "occurrence_number", "placer_group_number", "schedule_id",
            "request_event_reason", "appointment_reason", "appointment_type",
            "appointment_duration", "appointment_duration_units",
            "requested_start_date_time_range", "priority",
            "repeating_interval", "repeating_interval_duration",
            "placer_contact_person", "placer_contact_phone_number",
            "placer_contact_address", "placer_contact_location",
            "entered_by_person", "entered_by_phone_number",
            "entered_by_location", "parent_placer_appointment_id",
            "parent_filler_appointment_id", "placer_order_number",
            "filler_order_number",
        },
        ["RGS"] = new[]
        {
            "segment_id", "set_id", "segment_action_code", "resource_group_id",
        },
        ["AIS"] = new[]
        {
            "segment_id", "set_id", "segment_action_code",
            "universal_service_id", "start_datetime",
            "start_datetime_offset", "start_datetime_offset_units",
            "duration", "duration_units", "allow_substitution_code",
            "filler_status_code", "placer_supplemental_info",
            "filler_supplemental_info",
        },
        ["AIG"] = new[]
        {
            "segment_id", "set_id", "segment_action_code", "resource_id",
            "resource_type", "resource_group", "resource_quantity",
            "resource_quantity_units", "start_datetime",
            "start_datetime_offset", "start_datetime_offset_units",
            "duration", "duration_units", "allow_substitution_code",
            "filler_status_code",
        },
        ["AIL"] = new[]
        {
            "segment_id", "set_id", "segment_action_code",
            "location_resource_id", "location_type", "location_group",
            "start_datetime", "start_datetime_offset",
            "start_datetime_offset_units", "duration", "duration_units",
            "allow_substitution_code", "filler_status_code",
        },
        ["APR"] = new[]
        {
            "segment_id", "time_selection_criteria",
            "resource_selection_criteria", "location_selection_criteria",
            "slot_spacing_criteria", "filler_override_criteria",
        },
        ["AIP"] = new[]
        {
            "segment_id", "set_id", "segment_action_code",
            "personnel_resource_id", "resource_type", "resource_group",
            "start_datetime", "start_datetime_offset",
            "start_datetime_offset_units", "duration", "duration_units",
            "allow_substitution_code", "filler_status_code",
        },
        ["FT1"] = new[]
        {
            "segment_id", "set_id", "transaction_id",
            "transaction_batch_id", "transaction_date",
            "transaction_posting_date", "transaction_type",
            "transaction_code", "transaction_description",
            "transaction_description_alt", "transaction_quantity",
            "transaction_amount_extended", "transaction_amount_unit",
            "department_code", "health_plan_id", "insurance_amount",
            "assigned_patient_location", "fee_schedule", "patient_type",
            "diagnosis_code", "performed_by_code", "ordered_by_code",
            "unit_cost", "filler_order_number", "entered_by_code",
            "procedure_code", "procedure_code_modifier",
            "advanced_beneficiary_notice_code",
            "medically_necessary_duplicate_procedure_reason",
            "ndc_code", "payment_reference_id", "transaction_reference_key",
        },
        ["PR1"] = new[]
        {
            "segment_id", "set_id", "procedure_coding_method",
            "procedure_code", "procedure_description",
            "procedure_date_time", "procedure_functional_type",
            "procedure_minutes", "anesthesiologist", "anesthesia_code",
            "anesthesia_minutes", "surgeon", "procedure_practitioner",
            "consent_code", "procedure_priority",
            "associated_diagnosis_code", "procedure_code_modifier",
            "procedure_drg_type", "tissue_type_code",
            "procedure_identifier", "procedure_action_code",
        },
        ["ACC"] = new[]
        {
            "segment_id", "accident_date_time", "accident_code",
            "accident_location", "auto_accident_state",
            "accident_job_related_indicator", "accident_death_indicator",
            "entered_by", "accident_description", "brought_in_by",
            "police_notified_indicator", "accident_address",
        },
        ["GP1"] = new[]
        {
            "segment_id", "type_of_bill_code", "revenue_code",
            "overall_claim_disposition_code", "oce_edits_per_visit_code",
            "outlier_type", "outlier_days", "outlier_cost",
            "reimbursement_approval_indicator",
        },
        ["GP2"] = new[]
        {
            "segment_id", "revenue_code", "number_of_service_units",
            "charge", "reimbursement_action_code",
            "denial_or_rejection_code", "oce_edit_code",
            "ambulatory_payment_classification", "modifier_edit_code",
            "payment_adjustment_code", "packaging_status_code",
            "expected_cms_payment_amount", "reimbursement_type_code",
            "co_pay_amount", "pay_rate_per_service_unit",
        },
        ["CDM"] = new[]
        {
            "segment_id", "primary_key_value", "charge_code_alias",
            "charge_description_short", "charge_description_long",
            "description_override_indicator", "exploding_charges",
            "procedure_code", "active_inactive_flag", "inventory_number",
            "resource_load", "contract_number", "contract_organization",
            "room_fee_indicator",
        },
        ["PRC"] = new[]
        {
            "segment_id", "primary_key_value", "facility_id", "department",
            "valid_patient_classes", "price", "formula", "minimum_quantity",
            "maximum_quantity", "minimum_price", "maximum_price",
            "effective_start_date", "effective_end_date",
            "price_override_flag", "billing_category", "chargeable_flag",
            "active_inactive_flag", "cost", "charge_on_indicator",
        },
        ["ORC"] = new[]
        {
            "segment_id", "order_control", "placer_order_number",
            "filler_order_number", "placer_group_number", "order_status",
            "response_flag", "quantity_timing", "parent",
            "datetime_of_transaction", "entered_by", "verified_by",
            "ordering_provider", "enterer_location", "call_back_phone_number",
            "order_effective_datetime", "order_control_code_reason",
            "entering_organization", "entering_device", "action_by",
            "advanced_beneficiary_notice_code", "ordering_facility_name",
            "ordering_facility_address", "ordering_facility_phone_number",
            "ordering_provider_address", "order_status_modifier",
            "advanced_beneficiary_notice_override_reason",
            "filler_expected_availability_datetime", "confidentiality_code",
            "order_type", "enterer_authorization_mode",
            "parent_universal_service_identifier",
        },
        ["OBR"] = new[]
        {
            "segment_id", "set_id", "placer_order_number",
            "filler_order_number", "universal_service_id", "priority",
            "requested_datetime", "observation_datetime",
            "observation_end_datetime", "collection_volume",
            "collector_identifier", "specimen_action_code", "danger_code",
            "relevant_clinical_information", "specimen_received_datetime",
            "specimen_source", "ordering_provider",
            "order_callback_phone_number", "placer_field_1",
            "placer_field_2", "filler_field_1", "filler_field_2",
            "results_rpt_status_change_datetime", "charge_to_practice",
            "diagnostic_serv_sect_id", "result_status", "parent_result",
            "quantity_timing", "result_copies_to", "parent",
            "transportation_mode", "reason_for_study",
            "principal_result_interpreter", "assistant_result_interpreter",
            "technician", "transcriptionist", "scheduled_datetime",
            "number_of_sample_containers",
            "transport_logistics_of_collected_sample",
            "collectors_comment", "transport_arrangement_responsibility",
            "transport_arranged", "escort_required",
            "planned_patient_transport_comment", "procedure_code",
            "procedure_code_modifier",
            "placer_supplemental_service_information",
            "filler_supplemental_service_information",
            "medically_necessary_duplicate_procedure_reason",
            "result_handling", "parent_universal_service_identifier",
        },
        ["RXO"] = new[]
        {
            "segment_id", "requested_give_code",
            "requested_give_amount_minimum", "requested_give_amount_maximum",
            "requested_give_units", "requested_dosage_form",
            "provider_pharmacy_instructions",
            "provider_administration_instructions", "deliver_to_location",
            "allow_substitutions", "requested_dispense_code",
            "requested_dispense_amount", "requested_dispense_units",
            "number_of_refills", "ordering_providers_dea_number",
            "pharmacist_verifier_id", "needs_human_review",
            "requested_give_per", "requested_give_strength",
            "requested_give_strength_units", "indication",
            "requested_give_rate_amount", "requested_give_rate_units",
            "total_daily_dose", "supplementary_code",
            "requested_drug_strength_volume",
            "requested_drug_strength_volume_units",
            "pharmacy_order_type", "dispensing_interval",
            "medication_instance_identifier", "segment_group_id",
        },
        ["RXR"] = new[]
        {
            "segment_id", "route", "administration_site",
            "administration_device", "administration_method",
            "routing_instruction", "administration_site_modifier",
        },
        ["RXE"] = new[]
        {
            "segment_id", "quantity_timing", "give_code",
            "give_amount_minimum", "give_amount_maximum", "give_units",
            "give_dosage_form", "provider_administration_instructions",
            "deliver_to_location", "substitution_status",
            "dispense_amount", "dispense_units", "number_of_refills",
            "ordering_providers_dea_number", "pharmacist_verifier_id",
            "prescription_number", "number_of_refills_remaining",
            "number_of_refills_doses_dispensed",
            "datetime_of_most_recent_refill", "total_daily_dose",
            "needs_human_review", "special_dispensing_instructions",
            "give_per", "give_rate_amount", "give_rate_units",
            "give_strength", "give_strength_units", "give_indication",
            "dispense_package_size", "dispense_package_size_unit",
            "dispense_package_method", "supplementary_code",
            "original_order_date_time", "give_drug_strength_volume",
            "give_drug_strength_volume_units",
            "controlled_substance_schedule", "formulary_status",
            "pharmaceutical_substance_alternative",
            "pharmacy_of_most_recent_fill", "initial_dispense_amount",
            "dispensing_pharmacy", "dispensing_pharmacy_address",
            "deliver_to_patient_location", "deliver_to_address",
            "pharmacy_order_type", "pharmacist_verifier_id_2",
        },
        ["RXD"] = new[]
        {
            "segment_id", "dispense_sub_id_counter", "dispense_give_code",
            "date_time_dispensed", "actual_dispense_amount",
            "actual_dispense_units", "actual_dosage_form",
            "prescription_number", "number_of_refills_remaining",
            "dispense_notes", "dispensing_provider", "substitution_status",
            "total_daily_dose", "dispense_to_location",
            "needs_human_review", "special_dispensing_instructions",
            "actual_strength", "actual_strength_unit",
            "substance_lot_number", "substance_expiration_date",
            "substance_manufacturer_name", "indication",
            "dispense_package_size", "dispense_package_size_unit",
            "dispense_package_method", "supplementary_code",
            "initiating_location", "packaging_initiating_location",
            "actual_drug_strength_volume",
            "actual_drug_strength_volume_units", "dispense_to_pharmacy",
            "dispense_to_pharmacy_address", "pharmacy_order_type",
            "dispense_type", "pharmacy_phone_number",
        },
        ["RXG"] = new[]
        {
            "segment_id", "give_sub_id_counter", "dispense_sub_id_counter",
            "quantity_timing", "give_code", "give_amount_minimum",
            "give_amount_maximum", "give_units", "give_dosage_form",
            "administration_notes", "substitution_status",
            "deliver_to_location", "needs_human_review",
            "special_administration_instructions", "give_per",
            "give_rate_amount", "give_rate_units", "give_strength",
            "give_strength_units", "substance_lot_number",
            "substance_expiration_date", "substance_manufacturer_name",
            "indication", "give_drug_strength_volume",
            "give_drug_strength_volume_units",
            "controlled_substance_schedule", "formulary_status",
            "pharmacy_order_type", "dispense_to_pharmacy",
            "dispense_to_pharmacy_address", "pharmacy_phone_number",
            "dispense_type",
        },
        ["RXA"] = new[]
        {
            "segment_id", "give_sub_id_counter",
            "administration_sub_id_counter",
            "date_time_start_of_administration",
            "date_time_end_of_administration", "administered_code",
            "administered_amount", "administered_units",
            "administered_dosage_form", "administration_notes",
            "administering_provider", "administered_at_location",
            "administered_per", "administered_strength",
            "administered_strength_units", "substance_lot_number",
            "substance_expiration_date", "substance_manufacturer_name",
            "indication", "completion_status", "action_code",
            "system_entry_date_time", "administered_drug_strength_volume",
            "administered_drug_strength_volume_units",
            "administered_barcode_identifier", "pharmacy_order_type",
            "administering_pharmacy_address", "administered_tag_identifier",
        },
        ["TQ1"] = new[]
        {
            "segment_id", "set_id", "quantity", "repeat_pattern",
            "explicit_time", "relative_time_and_units", "service_duration",
            "start_date_time", "end_date_time", "priority",
            "condition_text", "text_instruction", "conjunction",
            "occurrence_duration", "total_occurrences",
        },
        ["TQ2"] = new[]
        {
            "segment_id", "set_id", "sequence_result_flag",
            "related_placer_number", "related_filler_number",
            "related_placer_group_number", "sequence_condition_code",
            "cyclic_entry_data_request", "sequence_condition_time_interval",
            "cyclic_group_maximum_number_of_repeats",
            "special_service_request_relationship",
        },
        ["SPM"] = new[]
        {
            "segment_id", "set_id", "specimen_id", "specimen_parent_ids",
            "specimen_type", "specimen_type_modifier", "specimen_additives",
            "specimen_collection_method", "specimen_source_site",
            "specimen_source_site_modifier", "specimen_collection_site",
            "specimen_role", "specimen_collection_amount",
            "grouped_specimen_count", "specimen_description",
            "specimen_handling_code", "specimen_risk_code",
            "specimen_collection_date_time", "specimen_received_date_time",
            "specimen_expiration_date_time", "specimen_availability",
            "specimen_reject_reason", "specimen_quality",
            "specimen_appropriateness", "specimen_condition",
            "specimen_current_quantity", "number_of_specimen_containers",
            "container_type", "container_condition", "specimen_child_role",
            "accession_id", "other_specimen_id", "shipment_id",
        },
        ["SAC"] = new[]
        {
            "segment_id", "external_accession_identifier",
            "accession_identifier", "container_identifier",
            "primary_sample_container_id",
            "equipment_container_identifier", "specimen_source",
            "registration_date_time", "container_status", "carrier_type",
            "carrier_identifier", "position_in_carrier", "tray_type",
            "tray_identifier", "position_in_tray", "location",
            "container_height", "container_diameter", "barrier_delta",
            "bottom_delta", "container_volume",
            "available_specimen_volume", "initial_specimen_volume",
            "volume_units", "separator_type", "cap_type", "additive",
            "specimen_component", "dilution_factor", "treatment",
            "temperature", "hemolysis_index", "hemolysis_index_units",
            "lipemia_index", "lipemia_index_units", "icterus_index",
            "icterus_index_units", "fibrin_index", "fibrin_index_units",
            "system_induced_contaminants", "drug_interference",
            "artificial_blood", "special_handling_code",
            "other_environmental_factors",
        },
        ["LOC"] = new[]
        {
            "segment_id", "primary_key_value", "location_description",
            "location_type", "organization_name", "location_address",
            "location_phone", "license_number", "location_equipment",
            "location_service_code",
        },
        ["LDP"] = new[]
        {
            "segment_id", "primary_key_value", "location_department",
            "location_service", "specialty_type", "valid_patient_classes",
            "active_inactive_flag", "activation_date", "inactivation_date",
            "inactivated_reason", "visiting_hours", "contact_phone",
            "location_cost_center",
        },
        ["LCH"] = new[]
        {
            "segment_id", "primary_key_value", "segment_action_code",
            "segment_unique_key", "location_characteristic_id",
            "location_characteristic_value",
        },
        ["LCC"] = new[]
        {
            "segment_id", "primary_key_value", "location_department",
            "accommodation_type", "charge_code",
        },
        ["TXA"] = new[]
        {
            "segment_id", "set_id", "document_type",
            "document_content_presentation", "activity_date_time",
            "primary_activity_provider_code", "origination_date_time",
            "transcription_date_time", "edit_date_time", "originator_code",
            "assigned_document_authenticator", "transcriptionist_code",
            "unique_document_number", "parent_document_number",
            "placer_order_number", "filler_order_number",
            "unique_document_file_name", "document_completion_status",
            "document_confidentiality_status",
            "document_availability_status", "document_storage_status",
            "document_change_reason", "authentication_person_time_stamp",
            "distributed_copies", "folder_assignment", "document_title",
            "agreed_due_date_time",
        },
        ["ADD"] = new[] { "segment_id", "addendum_continuation_pointer" },
        ["MSA"] = new[]
        {
            "segment_id", "acknowledgment_code", "message_control_id",
            "text_message", "expected_sequence_number",
            "delayed_acknowledgment_type", "error_condition",
            "message_waiting_number", "message_waiting_priority",
        },
        ["ERR"] = new[]
        {
            "segment_id", "error_code_and_location", "error_location",
            "hl7_error_code", "severity", "application_error_code",
            "application_error_parameter", "diagnostic_information",
            "user_message", "inform_person_indicator", "override_type",
            "override_reason_code", "help_desk_contact_point",
        },
        ["NTE"] = new[]
        {
            "segment_id", "set_id", "source_of_comment", "comment",
            "comment_type",
        },
        ["SFT"] = new[]
        {
            "segment_id", "software_vendor_organization",
            "software_certified_version", "software_product_name",
            "software_binary_id", "software_product_information",
            "software_install_date",
        },
        ["UAC"] = new[]
        {
            "segment_id", "user_authentication_credential_type_code",
            "user_authentication_credential",
        },
        ["PRT"] = new[]
        {
            "segment_id", "participation_instance_id", "action_code",
            "action_reason", "participation", "participation_person",
            "participation_person_provider_type",
            "participant_organization_unit_type", "participant_address",
            "participant_telecommunication_address", "participant_device",
            "participant_begin_date_time", "participant_end_date_time",
            "participant_qualitative_duration", "participant_address_2",
            "participant_telecommunication_address_2",
        },
        ["FHS"] = new[]
        {
            "segment_id", "file_field_separator",
            "file_encoding_characters", "file_sending_application",
            "file_sending_facility", "file_receiving_application",
            "file_receiving_facility", "file_creation_date_time",
            "file_security", "file_name_id", "file_header_comment",
            "file_control_id", "reference_file_control_id",
            "file_sending_network_address",
            "file_receiving_network_address",
        },
        ["FTS"] = new[] { "segment_id", "file_batch_count", "file_trailer_comment" },
        ["BHS"] = new[]
        {
            "segment_id", "batch_field_separator",
            "batch_encoding_characters", "batch_sending_application",
            "batch_sending_facility", "batch_receiving_application",
            "batch_receiving_facility", "batch_creation_date_time",
            "batch_security", "batch_name_id_type", "batch_comment",
            "batch_control_id", "reference_batch_control_id",
            "batch_sending_network_address",
            "batch_receiving_network_address",
        },
        ["BTS"] = new[] { "segment_id", "batch_message_count", "batch_comment", "batch_totals" },
        ["DSC"] = new[] { "segment_id", "continuation_pointer", "continuation_style" },
    };
}
